# Site settings
title: Soo Ahn Lee, Ph.D. candidate
baseurl: ""
url: "https://github.com/SooAhnLee/sooahnlee.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Soo Ahn Lee
  desc: Ph.D. candidate at Sungkyunkwan University
  email: sooahnlee23@gmail.com
  selfie: assets/img/LeeSA.jpeg

# social
social:
  email: sooahnlee23@gmail.com
  # behance:
  # bitbucket:
 # dribbble:
 # facebook: Test
 # flickr:
  github: https://github.com/SooAhnLee
 # google_plus:
 # instagram:
#  keybase:
 # linkedin: https://www.linkedin.com/in/kssim/ 
 # pinterest:
 # reddit:
 # soundcloud:
 # stack_exchange:
 # steam:
 # tumblr:
 # gitlab:
  twitter: @SooAhnLee
 # vimeo:
 # wordpress:
 # youtube:
 # default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
